### ISSUE TITLE
Users can see problems they don't have permission for if they have the link

### ISSUE THREAD

**Issue by VeniVidiVici42** [USMCA/website#21]

**Comment by TaisukeYasuda** [comment]
I should have implemented this -- did you remember to refresh? and if so, what are the permissions of the users in question?

**Comment by VeniVidiVici42** [comment]
A fresh account (bob the builder, bog.tro123 at gmail.com) can view the following problem:

http://usmca.herokuapp.com/view-problem/59b48680feaae4001265c758

which is from the public database. It looks like trying to access problems from the competition databases correctly gives an "unauthorized access to problem" message.

**Comment by TaisukeYasuda** [comment]
Fixed, closing. Please reopen if it's still wrong.
